# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [3]:
import numpy as np
import random as rd

In [17]:
arr=np.array([[rd.randint(1,20) for _ in range(1,26)]])
arr.shape=(5,5)

In [18]:
print(arr)

[[13  5 17  8 14]
 [16 19  7 16  6]
 [12 13 20 18  3]
 [ 7 12  9 20 11]
 [ 7  9  3 10  3]]


In [20]:
arr[2]=1

In [21]:
print(arr)

[[13  5 17  8 14]
 [16 19  7 16  6]
 [ 1  1  1  1  1]
 [ 7 12  9 20 11]
 [ 7  9  3 10  3]]


In [23]:
arr1=np.array([i for i in range(1,17)])
arr1.shape=(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [26]:
for i in range(4):
    print(arr1[i][i])
    arr1[i][i]=0

print(arr1)

1
6
11
16
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [33]:
arr=np.array([i for i in range(1,37)])
arr.shape=(6,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]



[[31 32 33 34 35 36]]


In [48]:
print(arr[ 2:5,1:4])

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [54]:
arr1=np.array([rd.randint(0,100) for _ in range(25)]).reshape(5,5)
print(arr1)

[[55 54 80 93 96]
 [33 50 54 78 37]
 [24 66  7 32 61]
 [ 8 12 16 65 99]
 [78 34 38  3 93]]


In [66]:
arr2=[]
for i in range(5):
    for j in range(5):
        if i==0 or j==0 or i==4 or j==4:
            arr2.append(int(arr1[i][j]))

print(arr2)

[55, 54, 80, 93, 96, 33, 37, 24, 61, 8, 99, 78, 34, 38, 3, 93]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [74]:
arr1=np.array([rd.randint(1,50) for _ in range(12)]).reshape(3,4)
arr2=np.array([rd.randint(1,25) for _ in range(12)]).reshape(3,4)
print(np.add(arr1,arr2))
print()
print(arr1-arr2)
print()
print(arr1*arr2)
print()
print(arr1/arr2)



[[20 29 32 72]
 [42 23 48 65]
 [26 67 45 67]]

[[ 12  -7  24  28]
 [ 16  -9   2  15]
 [-24  27  37  31]]

[[  64  198  112 1100]
 [ 377  112  575 1000]
 [  25  940  164  882]]

[[ 4.          0.61111111  7.          2.27272727]
 [ 2.23076923  0.4375      1.08695652  1.6       ]
 [ 0.04        2.35       10.25        2.72222222]]


In [78]:
print(arr1)
row_sum=np.sum(arr1,axis=1)
col_sum=np.sum(arr1,axis=0)
print(row_sum,col_sum)

[[16 11 28 50]
 [29  7 25 40]
 [ 1 47 41 49]]
[105 101 138] [ 46  65  94 139]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [89]:
arr=np.array([[rd.randint(1,20) for _ in range(1,26)]])
arr.shape=(5,5)
mean=arr.mean()
median=np.median(arr)
sd=arr.std()
print(mean,median,sd)

10.4 12.0 5.67097875150313


In [97]:
arr=np.arange(1,10).reshape(3,3)
norm=(arr-arr.mean())/arr.std()
print(norm)
print(norm.mean())
print(norm.std())

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0
1.0



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [100]:
arr2=np.array([10,20,10])

new_arr=arr+arr2
print(arr)
print()
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[11 22 13]
 [14 25 16]
 [17 28 19]]


In [108]:
arr1=np.array([rd.randint(10,30) for _ in range(1,17)])
arr1.shape=(4,4)
print(arr1)
arr2=np.array([10,20,10,30])
print(arr2)
print()

new_arr=arr1-arr2
print(new_arr)

[[18 17 24 14]
 [28 22 11 21]
 [14 25 30 12]
 [30 18 10 23]]
[10 20 10 30]

[[  8  -3  14 -16]
 [ 18   2   1  -9]
 [  4   5  20 -18]
 [ 20  -2   0  -7]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [15]:
def deterrminant(arr):
    return np.linalg.det(arr)
arr=np.array([[1,2,1],[6,8,7],[4,5,9]]).reshape(3,3)
det=deterrminant(arr)
print(f"determinant={det:.2f}")

determinant=-17.00


In [16]:
def inverse(arr):
    return np.linalg.inv(arr)
inv=inverse(arr)
print(inv)

[[-2.17647059  0.76470588 -0.35294118]
 [ 1.52941176 -0.29411765  0.05882353]
 [ 0.11764706 -0.17647059  0.23529412]]


In [17]:
def eigenvals(arr):
    return np.linalg.eigvals(arr)
ev=eigenvals(arr)
print(ev)

[15.47312295 -0.37819365  2.90507071]


In [28]:
arr1=np.random.randint(1,10,6).reshape(2,3)
arr2=np.random.randint(1,10,6).reshape(3,2)
print(arr1,"\n\n",arr2)
mularr=np.matmul(arr1,arr2)
print()
print(mularr)

[[8 8 5]
 [8 1 4]] 

 [[9 2]
 [2 9]
 [3 4]]

[[103 108]
 [ 86  41]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [33]:
arr=np.random.randint(1,10,9).reshape(3,3)
print(arr)

arr=arr.reshape(1,9)
print()
print(arr)

arr=arr.reshape(9,1)
print()
print(arr)

[[4 2 4]
 [1 8 9]
 [9 5 2]]

[[4 2 4 1 8 9 9 5 2]]

[[4]
 [2]
 [4]
 [1]
 [8]
 [9]
 [9]
 [5]
 [2]]


In [39]:
arr=np.random.randint(1,10,25).reshape(5,5)
print(arr)
print()
arr=arr.flatten()
print(arr)
arr=arr.reshape(5,5)
print()
print(arr)

[[2 6 2 2 2]
 [8 7 2 6 2]
 [9 7 8 9 4]
 [1 3 3 1 8]
 [4 1 7 6 9]]

[2 6 2 2 2 8 7 2 6 2 9 7 8 9 4 1 3 3 1 8 4 1 7 6 9]

[[2 6 2 2 2]
 [8 7 2 6 2]
 [9 7 8 9 4]
 [1 3 3 1 8]
 [4 1 7 6 9]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [41]:
for i in range(5):
    for j in range(5):
        if i==0 or j==0 or i==4 or j==4:
            print(arr[i][j])

2
6
2
2
2
8
2
9
4
1
8
4
1
7
6
9


In [45]:
arr=np.random.randint(1,100,16).reshape(4,4)
print(arr)
arr=arr[arr>=10]
print()
print(arr)

[[85  4 63  6]
 [37 22  6 27]
 [93 61 78  4]
 [28 46 77 72]]

[85 63 37 22 27 93 61 78 28 46 77 72]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.


In [9]:
students=np.array([["Jnanesh",19,65.00],["AK",20,56.00],["Kaverappa",69,300.0]], dtype=object)
print(students)
sorted_students=students[np.argsort(students[:,1].astype(int))]
print(sorted_students)

[['Jnanesh' 19 65.0]
 ['AK' 20 56.0]
 ['Kaverappa' 69 300.0]]
[['Jnanesh' 19 65.0]
 ['AK' 20 56.0]
 ['Kaverappa' 69 300.0]]
